### PR TITLE
Initial import

### PR DESCRIPTION
**Pull request by sagikazarmark**
Initial importing the core.

Some tasks before merging:

- [x] Order of paramteres (see #1)
- [x] Version constant (used in configuration user agent)
- [x] HttpAdapterFactory
- [x] Streams

Things to discuss:

- [x] Is kept alive (I renamed `getKeepAlive` to `isKeptAlive` in Configuration)
- [x] Timeout float->integer (Timeout is in seconds, why float then?)

### CODE REVIEW

**Comment by egeloen** [comment]
> Is kept alive (I renamed getKeepAlive to isKeptAlive in Configuration)

:+1: for `isKeepAlive`

> Timeout float->integer (Timeout is in seconds, why float then?)

Because all adapters is able to deal with milliseonds. See https://github.com/egeloen/ivory-http-adapter/blob/master/tests/AbstractHttpAdapterTest.php#L546-L552

**Comment by sagikazarmark** [comment]
To be precise, it is `isKeptAlive`, not `isKeepAlive`.

Miliseconds: `10.1s` or `10100 ms`

**Comment by egeloen** [comment]
Yes I mean `isKeptAlive` :) And Miliseonds: `10.1s`

**Comment by sagikazarmark** [comment]
Fine, that is float indeed.

**Comment by sagikazarmark** [comment]
Is there anything else? IMO we are absolutely out of the "initial" phase. If there is anything more we want to change, we can do it later.

**Comment by egeloen** [comment]
Merged!

**Pull request merged**
